### ISSUE TITLE
Best/Worst case estimation is faulty

### ISSUE THREAD

**Issue by Autissima** [MrPotatoTIAB/Mee6IntegrationProject#1]
Since it uses a floor function, there are cases where the estimation is wrong, f.e.:

34 XP left, then floor(34/25)=1 but that's not possible, since a message gives 25 at best.
>=15 XP left, then it'll return that you need 0 messages, and not 1.

This should round up, not down.

**Comment by MrPotatoTIAB** [comment]
should be fixed now.
